
def create_valid_pdf(filename="tests/test_doc.pdf"):
    # Minimal PDF with "Hello World"
    # Based on a standard minimal example
    content = (
        b"%PDF-1.1\n"
        b"1 0 obj\n"
        b"<<\n"
        b"  /Type /Catalog\n"
        b"  /Pages 2 0 R\n"
        b">>\n"
        b"endobj\n"
        b"2 0 obj\n"
        b"<<\n"
        b"  /Type /Pages\n"
        b"  /Kids [3 0 R]\n"
        b"  /Count 1\n"
        b"  /MediaBox [0 0 300 144]\n"
        b">>\n"
        b"endobj\n"
        b"3 0 obj\n"
        b"<<\n"
        b"  /Type /Page\n"
        b"  /Parent 2 0 R\n"
        b"  /Resources\n"
        b"  <<\n"
        b"    /Font\n"
        b"    <<\n"
        b"      /F1\n"
        b"      <<\n"
        b"        /Type /Font\n"
        b"        /Subtype /Type1\n"
        b"        /BaseFont /Times-Roman\n"
        b"      >>\n"
        b"    >>\n"
        b"  >>\n"
        b"  /Contents 4 0 R\n"
        b">>\n"
        b"endobj\n"
        b"4 0 obj\n"
        b"<<\n"
        b"  /Length 55\n"
        b">>\n"
        b"stream\n"
        b"BT\n"
        b"/F1 18 Tf\n"
        b"0 0 Td\n"
        b"(Hello World This is a test document with text content) Tj\n"
        b"ET\n"
        b"endstream\n"
        b"endobj\n"
        b"xref\n"
        b"0 5\n"
        b"0000000000 65535 f \n"
        b"0000000009 00000 n \n"
        b"0000000062 00000 n \n"
        b"0000000187 00000 n \n"
        b"0000000390 00000 n \n"
        b"trailer\n"
        b"<<\n"
        b"  /Root 1 0 R\n"
        b"  /Size 5\n"
        b">>\n"
        b"startxref\n"
        b"494\n"
        b"%%EOF\n"
    )

    with open(filename, "wb") as f:
        f.write(content)
    print(f"Created valid PDF at {filename}")

if __name__ == "__main__":
    create_valid_pdf()
